import { NgModule } from '@angular/core';
import {
  ArrowLeft,
  BookOpen,
  Calendar,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  Goal,
  LayoutGrid,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  LucideAngularModule,
  Medal,
  Settings,
  Shield,
  Target,
  Trophy,
  UserPlus,
  Users,
  Zap,
} from 'lucide-angular';

@NgModule({
  imports: [
    LucideAngularModule.pick({
      ArrowLeft,
      BookOpen,
      Calendar,
      CheckCircle,
      ChevronDown,
      ChevronRight,
      Goal,
      LayoutGrid,
      Loader2,
      Lock,
      LogIn,
      LogOut,
      Medal,
      Settings,
      Shield,
      Target,
      Trophy,
      UserPlus,
      Users,
      Zap,
    }),
  ],
  exports: [LucideAngularModule],
})
export class AppLucideIconsModule {}
